src/jannath/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^people/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    url(r'^people/', include('people.urls'))
)

src/people/urls.py
from .views import LoginView, HomeView, ApplicationView, UserSearchView, \
    UserSearchResultView, BillSearchView, BillPayView, SuccessView, GenerateStatementView
import views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

urlpatterns = [

    url(r'^$', LoginView.as_view(), name='login'),
    url(r'^signup$', views.signUpForm, name='signup'),
    url(r'^registered$', views.signUpSuccess, name='registered'),
    url(r'^login_success$', login_required(HomeView.as_view()), name='login_success'),
    url(r'^new_application$', login_required(ApplicationView.as_view()), name='new_application'),
    # url(r'^applicationSuccess$', views.applicationSuccess, name='applicationSuccess'),
    url(r'^user_search$', login_required(UserSearchView.as_view()), name='user_search'),

    url(r'^user_account/(?P<appid>\S*)$', login_required(UserSearchResultView.as_view()), name='user_account'),
    url(r'^logout/$', views.logout_view, name='logout'),

    url(r'^bill_pay/(?P<app_id>\S*)$', login_required(BillPayView.as_view()), name='bill_pay'),
    # url(r'^rateofintrest/$', views.submit, name='rate_of_intrest'),
    url(r'^bill_search', login_required(BillSearchView.as_view()), name='bill_search'),
    url(r'^get_statements', login_required(GenerateStatementView.as_view()), name='get_statements'),
    # url(r'^monthbill$', views.monthbill, name='monthbill'),
    # url(r'^bill_paid/(?P<appid>\d+)/(?P<date>\S*)/(?P<samount>\d+)/(?P<total>\d+)/(?P<loanid>\d+)/(?P<rm_pp>\d+)/(?P<intrest>\d+)/(?P<eamount>\d+)/(?P<emi_no>\d+)/$',
    #     views.bill_paid, name='billpaid'),
    url(r'^test',views.test,name='test'),
    url(r'^success/(?P<app_id>\S*)', login_required(SuccessView.as_view()), name='success'),
    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^loan_amount_validation/$',
        views.get_org_account_balance,
        name='loan_amount_validation')
]

src/people/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _


# Create your models here.

class SignUp(models.Model):
    user = models.OneToOneField(User)
    date_of_birth = models.DateField()
    mobile_no = models.CharField(max_length=10)

    def __unicode__(self):
        return self.user.name


class Application(models.Model):
    full_name = models.CharField(max_length=40, verbose_name=_('full_name'))
    father_or_husband_name = models.CharField(max_length=20)
    nominee_name = models.CharField(max_length=20)
    date_of_birth = models.DateField()
    job = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    mobile_no = models.CharField(max_length=10)

    def __unicode__(self):
        return self.full_name


class Loan(models.Model):
    appid = models.ForeignKey(Application, related_name='apploan')
    loan_amount = models.IntegerField(default=0)
    emi_amount = models.IntegerField(default=0)
    no_of_emis = models.IntegerField(default=0)
    rate_of_intrest = models.FloatField(default=0.0)
    status = models.BooleanField(default=False)
    created_at = models.DateField(default=None)


class SpecialLoan(models.Model):
    appid = models.ForeignKey(Application, related_query_name='appsploan')
    special_loan_amount = models.IntegerField(default=0)
    special_intrest_amount = models.IntegerField(default=0)
    special_intrest_rate = models.FloatField(default=0.0)
    status = models.BooleanField(default=False)
    created_at = models.DateField(default=None)


class Bills(models.Model):
    appid = models.ForeignKey(Application, related_name='appbill')
    loanid = models.IntegerField(default=0)
    created_at = models.DateField(default=None)
    total = models.CharField(max_length=100)
    paid_emi = models.IntegerField(default=0)
    emi_no = models.IntegerField(default=0)
    rm_amount = models.IntegerField(default=0)
    interest_amount = models.FloatField(default=0.0)
    special_loan_amount = models.IntegerField(default=0)
    special_intrest = models.FloatField(default=0)
    penality = models.IntegerField(default=0)
    full_paid = models.FloatField(default=0.0)
    share_amount = models.IntegerField(default=0)


class SavingAccount(models.Model):
    appid = models.ForeignKey(Application, related_name='appacount')
    date = models.DateField()
    balance = models.FloatField(default=0.0)


class OrganisationAccount(models.Model):
    billid = models.ForeignKey(Bills, related_name='bill')
    bill_amount = models.FloatField(default=0.0)
    balance = models.FloatField(default=0.0)


class ExpenditureModel(models.Model):
    name = models.CharField(max_length=20)
    amount = models.FloatField(default=0.0)
    created_at = models.DateField(default=None)

src/people/forms.py
__author__ = 'qsslp231'

from bootstrap_datepicker.widgets import DatePicker

from django.utils.translation import ugettext_lazy as _
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth import authenticate

from .models import Application


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'password')


class SignUpForm(forms.Form):

    date_of_birth = forms.DateField(label=_("Date Of Birth"))
    mobile_no = forms.IntegerField(label=_("Mobile No"))

    # class Meta:
    #     model = SignUp
    #     fields = (_('date_of_birth'), _('mobile_no'))

    # def clean(self):
    #     print "CLeaning"
    #     raise forms.ValidationError("Testing")


class LoginForm(forms.Form):

    user_name = forms.CharField(label=_("User Name"), max_length=10)
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.errors:
            return
        username = self.cleaned_data.get('user_name')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError(_('Invalid Username or Password'))
            self.user_name = user
            return self.user_name


class UserSearchForm(forms.Form):
    id_or_full_name = forms.CharField(
        label=_("ID/Full Name"),
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Number/Name', 'type': 'char'})
    )

    def clean_id_or_full_name(self):
        return self.cleaned_data.get('id_or_full_name')

    def clean(self):
        if self.errors:
            return
        try:
            data = self.cleaned_data
            input_data = data.get('id_or_full_name')
            if input_data:
                if input_data.isdigit():
                    app1 = Application.objects.get(id=input_data)
                    user_account = SavingAccount.objects.filter(appid_id=app1.id).latest('id')
                    self.id_or_full_name = input_data
                else:
                    app1 = Application.objects.get(full_name=input_data)
                    user_account = SavingAccount.objects.filter(appid_id=app1.id).latest('id')
                    self.id_or_full_name = input_data
            else:
                self.add_error(
                    'id_or_full_name', _('Enter Application Number Or Full Name'))
                return
            if app1 and user_account:
                return self.id_or_full_name

        except Application.DoesNotExist:
            self.add_error('id_or_full_name', _('No Application Records Found'))


class DateInput(forms.DateInput):
    input_type = 'date'


class ApplicationForm(forms.Form):

        full_name = forms.CharField(label=_('Full name'))
        father_or_husband_name= forms.CharField(label=_('Father or Husband Name'))
        nominee_name = forms.CharField(label= _('Nominee Name'))
        date_of_birth = forms.DateField(label=_('Date of Birth'), widget=DateInput)
        job = forms.CharField(label=_('Job'))
        address = forms.CharField(label=_('Address'))
        mobile_no = forms.CharField(label=_('Mobile No'))


class LoanForm(forms.Form):
    loan_amount = forms.CharField(label=_("Loan Amount"))
    installment_amount = forms.CharField(label=_("Installment Amount"))
    number_of_emi = forms.CharField(label=_("Number Of Emi"))
    rate_of_intrest = forms.IntegerField(label=_("Rate Of Intrest"))


class SpecialLoanForm(forms.Form):
    special_loan_amount = forms.CharField(label=_("Special Loan Amount"))
    special_rate_of_intrest = forms.IntegerField(label=_("special Rate Of Intrest"))
    special_intrest_amount = forms.CharField(label=_("Special Intrest Amount"))


class AccountStatementForm(forms.Form):
    type = forms.ChoiceField(label=_('type'),
                             choices=[('loan', _('loan')),
                                      ('short appu', _('short appu')),
                                      ('monthly/yearly', _('monthly/yearly')),
                                      ('karchulu', _('karchulu')),
                                      ('labam_vivaralu', _('labam_vivaralu'))])
    from_date = forms.DateField(label=_('From Date'), widget=DateInput)
    to_date = forms.DateField(label=_('To Date'), widget=DateInput)


class ExpenditureForm(forms.Form):
    purpose = forms.CharField(label=_('purpose'))
    amount = forms.CharField(label=_('expense'))
    date = forms.DateField(label=_('Date'), widget=DateInput)


class TotalProfitForm(forms.Form):
    total_profit_amount = forms.CharField(label=_('expense'))


class BillSearchForm(forms.Form):
    id_or_full_name = forms.CharField(label=_("ID/Full Name"), required=False, widget=forms.TextInput(
        attrs={'placeholder': 'Number/Name', 'type': 'char'}))

    def clean_id_or_full_name(self):
        return self.cleaned_data.get('id_or_full_name')

    def clean(self):
        if self.errors:
            return
        try:
            data = self.cleaned_data
            input_data = data.get('id_or_full_name')
            if input_data:
                if input_data.isdigit():
                    try:
                        app1 = Application.objects.get(id=input_data)
                        self.id_or_full_name = app1.id
                        return self.id_or_full_name
                    except Application.DoesNotExist:
                            self.add_error(
                                'id_or_full_name', _('No Application with this Number')
                            )
                else:
                    try:
                        app1 = Application.objects.get(full_name=input_data)
                        self.id_or_full_name = app1.full_name
                        return self.id_or_full_name
                    except Application.DoesNotExist:
                        self.add_error(
                            'id_or_full_name', _('No Application with this Name')
                        )
            else:
                self.add_error(
                    'id_or_full_name', _('Enter Application Number Or Full Name'))

        except Exception as e:
            self.add_error('id_or_full_name', _('Something went Horribly Wrong'))

src/templates/SignUP.html
<!--<body>-->
<!--{% load i18n %}-->

<!--<h1>{{ title}}</h1>-->
<!--<div>-->
<!--<form method="POST" action="/people/registered">-->
    <!--{% csrf_token %}-->

    <!--{{user_form.as_p}}-->

    <!--{{ form.as_p }}-->


    <!--<input type="submit" value="register">-->

<!--</form>-->
<!--</div>-->

<html lang="en"><head>
<title>Log in | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">




<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=" login" data-admin-utc-offset="0">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name"><a href="/admin/">Sign UP</a></h1>

        </div>


    </div>
    <!-- END Header -->







    <!-- Content -->
    <div id="content" class="colM">







<div id="content-main">



<!--<form action="" method="post" id="logform"><input type="hidden" name="csrfmiddlewaretoken" value="ZRA0RSxZU88vMd4Az7nnPUT5ih6ECp6L12h4hL84EGHlSOtoQCb7k7XSOkQEPnWD">-->
  <!--<div class="form-row">-->

    <!--<label class="required" for="id_username">Username:</label> <input type="text" name="username" autofocus="" required="" id="id_username" maxlength="254">-->
  <!--</div>-->
  <!--<div class="form-row">-->

    <!--<label class="required" for="id_password">Password:</label> <input type="password" name="password" required="" id="id_password">-->
    <!--<input type="hidden" name="next" value="/admin/">-->
  <!--</div>-->
    <form method="POST" action="/people/">
        {% csrf_token %}

        {{user_form.as_p}}

        {{ form.as_p }}

    <input type="submit" value="register">

    </form>

  <!--<div class="submit-row">-->
    <!--<label>&nbsp;</label><input type="submit" value="Log in">-->
  <!--</div>-->
<!--</form>-->

</div>


        <br class="clear">
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->



</body></html>

src/templates/application.html
{% include "base.html" %}
{% load staticfiles %}
{% load i18n %}
<head xmlns="http://www.w3.org/1999/html">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Datepicker - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<div style="position:relative;top:300px;">
    <form method="POST" action=""  align="center" id="app_form">
        {% csrf_token %}
                {% for field in form %}
                    {{ field.errors }}
                    <div class="form-group">
                        <label class="col-sm-1 control-label" for="id_{{ field.name }}">{{ field.label }}</label>{{ field }}
                    </div>
                {% endfor %}
        <div id="error_msg" class="alert alert-danger" style="display:none;">
            <strong>{% trans 'Please enter 10-digit Mobile number' %}</strong>
        </div>
        <button id="app_id" type="submit" class="btn" >{% trans 'Submit' %}</button>
    </form>
</div>
<script src="{% static 'js/general.js' %}"></script>

src/templates/bill.html
{% load i18n %}
{% include "base.html" %}
<div style="position:relative;top:300px;left:550px;">
    {% if error %}
    <p style="color:red">{{ error }}</p>
    {% endif %}
    <form method="POST" action="{% url 'bill_search' %}">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
                {{ field.errors }}
                <div class="form-group">
                    <label class="col-sm-1 control-label" for="id_{{ field.name }}">{{ field.label }}</label>{{ field }}
                </div>
            {% endfor %}
        </fieldset>
        <button type="submit" class="btn" value="Bill Search" >{% trans 'Bill Search' %}</button>
    </form>
</div>

src/templates/bill_paid.html
{% include "base.html" %}
<body>
<h2>Bill Paid</h2>
<p>Please collect your bill</p>
</body>
</html>

src/templates/home.html
{% include "base.html" %}
<body>
    <form method="post" action="/people/home">
        {% csrf_token %}
        New application created successfully
        <br>
        <input type="submit" value="Home">
    </form>
</body>

src/templates/invalid.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h2>Your Login details are invalid</h2>
<p>Click <a href="/people/" >here</a>to login again</p>
</body>
</html>

src/templates/login_success.html
{% include "banner.html" %}
{% include "base.html" %}

src/templates/monthbill.html
{% load i18n %}
{% include "base.html" %}

<style>
    table, td {
        border: 2px solid black;
        border-collapse: collapse;
    }
    input[type='readonly'] {
        border: none;
        outline: none;
    }
    input[type=text] {
        display:none;
    }
    @media print {
      body * {
        visibility: hidden;
      }
      #section-to-print, #section-to-print * {
        visibility: visible;
      }
      #section-to-print {
        position: absolute;
        left: 0;
        top: 0;
      }
    }
</style>
<script>
    function myFun() {
        window.print()
    }
    var calculateTotal = function(){
        var values = $('.editable, .summate').map(function(i, el) { return el.value}).get();
        console.log("calculating total", values)
        var total = values.reduce(function(c, a){
            if(a){
                return c + parseFloat(a);
            } else {
                return c;
            }
        }, 0.0);
        $("#total_amount").val(total);
    }

    $(document).ready(function() {
        $('#edit_btn').click(function() {
            $('.editable').removeAttr("readonly");
        });
        $("input").change(function(){
            calculateTotal();
            $('.editable').attr('readonly', true);
        });

        setTimeout(function(){
            calculateTotal();
        }, 100);

        var validateUsername = function(e) {
        var a = [];
        var k = e.which;

        for (var i = 48; i < 58; i++)
            a.push(i);

        if (!(a.indexOf(k)>=0))
            e.preventDefault();
        };

        $('#id_share_amount').on('keypress', validateUsername);
        $('#id_full_paid').on('keypress', validateUsername);
        $('#id_penality').on('keypress', validateUsername);
    });

</script>
<div style="position:relative;top:300px;left:550px;">
<form method="POST" id="edit_form">
<div id="section-to-print">
    <span>{% trans 'App-Id' %}: {{name.id}}</span><br>
    <span>{% trans 'Full-Name' %} : {% blocktrans with name=name %} {{name}} {% endblocktrans %}</span>
    <p>{% trans 'Date' %}: {{date}}</p>
<br>
<table >
    <tr>
        <td>{% trans 'Share Amount' %} </td>
        <td>
            <input class="editable" name="share_amount" value="{{share_amount}}" id="id_share_amount" readonly>
        </td>
    </tr>
    <tr>
        <td>{% trans 'Loan Amount' %}
            <input value="({{loan_amount}})" readonly>
                {% trans 'total_emi_no' %}  ({{total_emi_no}})
        </td>
        <td></td>
    </tr>
    <tr>
        <td>{% trans 'emi amount' %}</td>
        <td>
            <input class="summate" value="{{emi_amount}}" readonly>
        </td>
    </tr>
    <tr>
        <td>{% trans 'paid loan amount' %} ({{paid_loan_amount}} )</td>
        <td></td>
    </tr>
    <tr>
        <td>{% trans 'Emi.No' %}    ({{emi_no}})</td>
        <td></td>
    </tr>
    <tr>
        <td>{% trans 'Intrest Amount' %}</td>
        <td>
            <input class="summate" value="{{intrest}}" readonly>
        </td>
    </tr>
    <tr>
        <td>{% trans 'Special Loan Amount' %}  ({{special_loan_amount}})</td>
        <td>
            <input class="summate" name="special_loan_amount" value="{{special_loan_amount}}" readonly>
        </td>
    </tr>
    <tr>
        <td>{% trans 'Special Intrest Amount' %} </td>
        <td>
            <input class="summate" name="special_intrest" value="{{special_intrest}}" readonly>
        </td>
    </tr>
    <tr>
        <td>{% trans 'Penality' %} </td>
        <td>
            <input class="editable" name="penality" id="id_penality" readonly>
        </td>
    </tr>
    <tr>
        <td>{% trans 'remaining debt' %}   ({{remaining_debt}})</td>
        <td>
            <!--<input type="readonly" value="{{remaining_debt}}">-->
            <!--<input value="{{remaining_debt}}">-->
        </td>
    </tr>
    <tr>
        <td>{% trans 'Full Paid' %}</td>
        <td>
            <input class="editable" name="full_paid" id="id_full_paid" readonly>
        </td>
    </tr>
    <tr>
        <td>{% trans 'Total' %}</td>
        <td>
            <input id="total_amount" name="total_amount" readonly>
        </td>
    </tr>
</table>
    </div>
<br>
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" id="print_btn" value="{% trans 'Print' %}" onClick="window.print()">
</form>
<input type="button" class="btn btn-primary" id="edit_btn" value="{% trans 'Edit Bill' %}">

</div>

src/templates/registered.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form method="post" action="/people/">
    {% csrf_token %}

    <p> Successfully Registered </p>

    <input type="submit" value="Login">

</form>
</body>
</html>

src/templates/success.html
{% load i18n %}
{% include "base.html" %}

<div style="position:relative;top:300px;left:550px;">
    <p>{% trans 'Your Application is saved and your id' %} {{id}}</p>
</div>

src/templates/useraccount.html
{% load i18n %}
{% include "base.html" %}
<div style="
    position: relative;
    top: 300;
    left: 550px;
">
    {% get_current_language as LANGUAGE_CODE %}
    <h4>{% trans 'App.No:' %} {{application_id}}</h4>
    <h4>{% trans 'Full Name :' %} {{name}}</h4>
    <h4>{% trans 'Balance:' %} {{balance}}</h4>
    <h4>{% trans 'Loan Amount' %} {{loan_amount}}</h4>
    <h4>{% trans 'Special Loan Amount' %} {{sp_loan_amount}}</h4>

    <button type="button"  class="btn btn-primary" value="Loan Form" id="loan_form_btn">{% trans 'Loan Form' %}</button>
    <button type="button"  class="btn btn-primary" value="Special Loan Form" id="special_loan_btn">{% trans 'Special Loan Form' %}</button>
    <button type="button"  class="btn btn-primary" value="Account Statement Form" id="account_statement_btn">{% trans 'Account Statement Form' %}</button>
    <div id="loan_msg" class="alert alert-danger" style="display:none;">
        <strong>{% trans 'loan already exists' %}</strong>
    </div>
    <div id="special_loan_msg" class="alert alert-danger" style="display:none;">
        <strong>{% trans 'Special loan already exists' %}</strong>
    </div>
    <form method="POST" id="loan_form" style="display:none;">
        {% csrf_token %}
            {{ forms.loan_form.as_p }}
        <input id="loan_btn" type="submit" class="btn" value="{% trans 'Submit' %}">

    </form>
    <form id="special_loan" method="POST" style="display:none;">
        {% csrf_token %}
        {{ forms.specialLoan_form.as_p }}
        <input id="special_loan_bttn" type="submit" class="btn" value="{% trans 'Submit' %}">
    </form>
    <form id="account_statement" method="POST" style="display:none;">
        {% csrf_token %}
        {{ forms.account_statement_form.as_p }}
        <input type="submit" class="btn" value="{% trans 'Submit' %}">
    </form>
    <div id="msg" class="alert alert-danger" style="display:none;"></div>
</div>

<script>
jQuery('#id_number_of_emi').focus(function(){
    var a = jQuery("#id_loan_amount").val();
    var b = jQuery("#id_installment_amount").val();

    if(a && b) {
        jQuery(this).val(a/b);
    }
})

jQuery('#id_special_intrest_amount').focus(function(){
    var a = jQuery("#id_special_loan_amount").val();
    var b = jQuery("#id_special_rate_of_intrest").val();

    if(a && b) {
        jQuery(this).val(a*(b/100));
    }
})

    $(document).ready(function() {
        var str = "{{loan_status}}";
            str1 = "{{special_loan_status}}";
        $("#loan_form_btn").click(function() {
            if (str.toString() == 'True')  {
                $("#special_loan").hide();
                $("#loan_msg").show();
                $("#special_loan").hide();
                $("#account_statement").hide();
            } else {
                $("#loan_form").show();
                $("#special_loan").hide();
                $("#account_statement").hide();
            }
            $("#msg").hide();
            $("#special_loan_msg").hide();
            });
        $("#special_loan_btn").click(function() {
            if (str1.toString() == 'True') {
                $("#special_loan_msg").show();
                $("#loan_form").hide();
                $("#account_statement").hide();
            } else {
                $("#special_loan").show();
                $("#loan_form").hide();
                $("#account_statement").hide();
                $("#special_loan_bttn").attr("disabled", false);
            }
            $("#msg").hide();
            $("#loan_msg").hide();
        });
        $("#account_statement_btn").click(function() {
            $("#special_loan").hide();
            $("#loan_form").hide();
            $("#account_statement").show();
            $("#msg").hide();
            $("#special_loan_msg").hide();
            $("#loan_msg").hide();

        });

        var validateUsername = function(e) {
        var a = [];
        var k = e.which;

        for (var i = 48; i < 58; i++)
            a.push(i);

        if (!(a.indexOf(k)>=0))
            e.preventDefault();
        };

        // loan details

        $('#id_loan_amount').on('keypress', validateUsername);
        $('#id_installment_amount').on('keypress', validateUsername);
        $("#id_number_of_emi").prop("readonly", true);
        $("#id_loan_amount").on('focus', function(){
            $("#msg").hide();
            $("#loan_btn").attr("disabled", false);
        });

        // special loan details

        $('#id_special_loan_amount').on('keypress', validateUsername);
        $("#id_special_intrest_amount").prop("readonly", true);
        $("#id_special_loan_amount").on('focus', function(){
            $("#msg").hide();
            $("#special_loan_bttn").attr("disabled", false);
        });

        var loanAmountValidation = function(response){
        $("#msg").hide();
        if(response.message){
            $("#msg").html(response.message);
            $("#msg").show();
            $("#loan_btn").attr("disabled", true);
            $("#special_loan_bttn").attr("disabled", true);
        }
    };

        var loanAmountForm = function(data, successFunc){
        $.ajax({
            url: window.registration_validation_url,
            data: data,
            dataType: 'json',
            success: function(data) {
                 successFunc(data);
            },
        })
    };

        $("#id_loan_amount").on('blur', function(e){
        var value = e.target.value;
        loanAmountForm({
            "loan_amount": value
        }, loanAmountValidation);
    });
    $("#id_special_loan_amount").on('blur', function(e){
        var value = e.target.value;
        loanAmountForm({
            "loan_amount": value
        }, loanAmountValidation);
    });

    });
    window.registration_validation_url = "{{ form_validation_url }}";
    $("#id_type Option[value='karchulu']").hide();
    $("#id_type Option[value='labam_vivaralu']").hide();
</script>

src/templates/usersearch.html
{% load i18n %}
{% include "base.html" %}
<div style="position:relative;top:300px;left:550px;">
    <form method="POST"  action="" >
        {% csrf_token %}
            <fieldset>
                {% for field in form %}
                    {{ field.errors }}
                    <div class="form-group">
                        <label class="col-sm-1 control-label" for="id_{{ field.name }}">{{ field.label }}</label>{{ field }}
                    </div>
                {% endfor %}
            </fieldset>
        <button type="submit" class="btn" >{% trans 'User Search' %}</button>
    </form>
</div>